### PR TITLE
Very small update 

### PR DESCRIPTION
**Pull request by Domaman202**
🤣🤣🤣

### CODE REVIEW

**Comment by CebbyS** [comment]
> 🤣🤣🤣

Hi, thank you very much for helping! I just want to know, what are your plans on these updates? Is there something particular in your mind?

**Comment by Domaman202** [comment]
Always happy to help! At the moment, I plan to implement utilities for working with groovy scripts.

**Comment by Domaman202** [comment]
ok, i did a little code refactoring

**Comment by Domaman202** [comment]
also added utilities for working with groovy

**Comment by Domaman202** [comment]
functions of the mod "Fabric Core Mods" were added (https://www.curseforge.com/minecraft/mc-mods/fabric-core-mods)

**Comment by Domaman202** [comment]
the register of liquids was added

**Comment by Domaman202** [comment]
and a few more utilities for working with liquids

**Comment by Domaman202** [comment]
this is still a small part of my plans for this mod 😉

**Comment by CebbyS** [comment]
I see, thank you very much!

**Pull request merged**
